
language: node_js
node_js:
- 7
dist: trusty
sudo: false
git:
  depth: 1
cache:
  directories:
  - node_modules
install:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install
script:
  - preact build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  - npm run lh -- --perf=90 --pwa=100 --seo=100 https://test-lh-check.firebaseapp.com